<?php
/*
 * @copyright   2018 Mautic Contributors. All rights reserved
 * @author      Mautic
 *
 * @link        http://mautic.org
 *
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 * 
 */

namespace MauticPlugin\MauticActivemqTransportBundle\Tests\Activemq;

use MauticPlugin\MauticActivemqTransportBundle\Activemq\Connector;

class ConnectorTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Connector
     */
    private $connector;

    protected function setUp(): void
    {
        $this->connector = new Connector();
        $this->connector
            ->setPassword('borg')
            ->setPartnerId('number7')
            ->setSlooceDomain('universe')
            ->setShortCodeField('scfi')
            ;

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetShortCodeField()
    {
        $this->assertEquals('scfi', $this->connector->getShortCodeField());
    }
}
