<?php
/*
 * @copyright   2018 Mautic Contributors. All rights reserved
 * @author      Mautic
 *
 * @link        http://mautic.org
 *
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 * 
 */

namespace MauticPlugin\MauticActivemqTransportBundle\Tests\Transport;

use MauticPlugin\MauticActivemqTransportBundle\Message\MtMessage;
use MauticPlugin\MauticActivemqTransportBundle\Activemq\Connector;

class ActivemqTransportTest extends \PHPUnit\Framework\TestCase
{
    /** @var Connector */
    private $connector;

    /** @var MtMessage */
    private $message;

    protected function setUp(): void
    {
        $this->connector = $this->createMock(Connector::class);
        $this->connector->expects($this->any())->method('sendMtMessage')->will($this->returnValue(['status'=>true]));

        $this->message = new MtMessage('test-message');
        $this->message->setContent('restistance is futile');

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testSendSms()
    {
        $this->markTestSkipped(/** @todo */);
    }
}
